// express-app-v4.18.2
GET http://localhost:3100/api/test-data?_records=3&_text_param=Hello%20World&_int_param=12345&_ts_param=2021-01-01T00:00:00.000Z&_bool_param=true

###

// django-app-v5.0.9
GET http://localhost:8000/api/test-data?_records=3&_text_param=Hello%20World&_int_param=12345&_ts_param=2021-01-01T00:00:00.000Z&_bool_param=true

###

// postgrest-v12.2.3
GET http://localhost:3000/rpc/test_func_v1?_records=3&_text_param=Hello%20World&_int_param=12345&_ts_param=2021-01-01T00:00:00.000Z&_bool_param=true

###

// fastapi-app-v0.103.2
GET http://localhost:8001/api/test-data?_records=3&_text_param=Hello%20World&_int_param=12345&_ts_param=2021-01-01T00:00:00.000Z&_bool_param=true

###

// fastify-app-v4.26.1
GET http://localhost:3101/api/test-data?_records=3&_text_param=Hello%20World&_int_param=12345&_ts_param=2021-01-01T00:00:00.000Z&_bool_param=true

###

// deno-app-v1.40.2
GET http://localhost:3102/api/test-data?_records=3&_text_param=Hello%20World&_int_param=12345&_ts_param=2021-01-01T00:00:00.000Z&_bool_param=true

###

// swoole-php-app-8.3.13
GET http://localhost:3103/api/test-data?_records=3&_text_param=Hello%20World&_int_param=12345&_ts_param=2021-01-01T00:00:00.000Z&_bool_param=true

###

// npgsqlrest-aot-v2.2.1
GET http://localhost:5000/api/test-data?_records=3&_text_param=Hello%20World&_int_param=12345&_ts_param=2021-01-01T00:00:00.000Z&_bool_param=true

###

// net8-npgsqlrest-jit-v2.12.1
GET http://localhost:5001/api/test-data?_records=3&_text_param=Hello%20World&_int_param=12345&_ts_param=2021-01-01T00:00:00.000Z&_bool_param=true

###

